"""Initial migration

Revision ID: 6cd4bbbbe76b
Revises: 3e4c09dc542b
Create Date: 2025-02-03 12:17:19.026550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd4bbbbe76b'
down_revision: Union[str, None] = '3e4c09dc542b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
